import type { Recipe } from './RecipePersistence';

export const SEED_RECIPES: Recipe[] = [
  {
    id: 'buttermilk-pancakes',
    title: 'Buttermilk Pancakes',
    servings: 4,
    ingredients: [
      { name: 'flour', quantity: 200, unit: 'g' },
      { name: 'buttermilk', quantity: 240, unit: 'ml' },
      { name: 'eggs', quantity: 2, unit: 'piece' },
      { name: 'sugar', quantity: 2, unit: 'tbsp' },
      { name: 'baking powder', quantity: 1, unit: 'tsp' },
      { name: 'salt', quantity: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Whisk flour, sugar, baking powder, and salt in a bowl.',
      'In a separate bowl, beat eggs and buttermilk together.',
      'Combine the wet and dry mixtures; stir until just combined (lumps are fine).',
      'Heat a non-stick skillet over medium heat and ladle on the batter.',
      'Cook 2 minutes per side, until bubbles set and edges look dry.',
      'Serve warm with maple syrup.',
    ],
    totalMinutes: 20,
    searchableIngredients: ['flour', 'buttermilk', 'eggs', 'sugar', 'baking powder', 'salt'],
  },
  {
    id: 'tomato-pasta',
    title: 'Tomato Pasta',
    servings: 2,
    ingredients: [
      { name: 'spaghetti', quantity: 200, unit: 'g' },
      { name: 'crushed tomatoes', quantity: 400, unit: 'g' },
      { name: 'garlic cloves', quantity: 2, unit: 'piece' },
      { name: 'olive oil', quantity: 2, unit: 'tbsp' },
      { name: 'basil leaves', quantity: 6, unit: 'piece' },
      { name: 'salt', quantity: 1, unit: 'tsp' },
    ],
    steps: [
      'Bring a large pot of salted water to a boil and cook spaghetti to al dente.',
      'Meanwhile, warm olive oil in a saucepan and sauté sliced garlic until fragrant.',
      'Pour in crushed tomatoes, season with salt, and simmer for 8 minutes.',
      'Drain pasta and toss it with the sauce.',
      'Tear basil over the top and serve.',
    ],
    totalMinutes: 25,
    searchableIngredients: ['spaghetti', 'crushed tomatoes', 'garlic', 'olive oil', 'basil', 'salt'],
  },
  {
    id: 'lemon-garlic-chicken-skillet',
    title: 'Lemon Garlic Chicken Skillet',
    servings: 2,
    ingredients: [
      { name: 'chicken', quantity: 400, unit: 'g' },
      { name: 'lemon', quantity: 1, unit: 'piece' },
      { name: 'garlic cloves', quantity: 4, unit: 'piece' },
      { name: 'butter', quantity: 2, unit: 'tbsp' },
      { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      { name: 'fresh parsley', quantity: 2, unit: 'tbsp' },
      { name: 'salt', quantity: 1, unit: 'tsp' },
    ],
    steps: [
      'Pat chicken dry and season both sides with salt.',
      'Heat olive oil in a skillet over medium-high heat.',
      'Sear chicken for 5–6 minutes per side until golden brown and cooked through.',
      'Remove chicken and add butter and garlic to the pan; cook 1 minute.',
      'Squeeze lemon juice into the pan and stir to combine.',
      'Return chicken to the pan, spoon sauce over it, and garnish with parsley.',
    ],
    totalMinutes: 25,
    searchableIngredients: ['chicken', 'lemon', 'garlic', 'butter', 'olive oil', 'parsley'],
  },
  {
    id: 'honey-soy-chicken-stir-fry',
    title: 'Honey Soy Chicken Stir-Fry',
    servings: 2,
    ingredients: [
      { name: 'chicken', quantity: 350, unit: 'g' },
      { name: 'soy sauce', quantity: 3, unit: 'tbsp' },
      { name: 'honey', quantity: 2, unit: 'tbsp' },
      { name: 'garlic cloves', quantity: 2, unit: 'piece' },
      { name: 'sesame oil', quantity: 1, unit: 'tbsp' },
      { name: 'spring onions', quantity: 3, unit: 'piece' },
      { name: 'sesame seeds', quantity: 1, unit: 'tbsp' },
    ],
    steps: [
      'Slice chicken into thin strips.',
      'Whisk soy sauce, honey, and minced garlic together in a small bowl.',
      'Heat sesame oil in a wok or large pan over high heat.',
      'Stir-fry chicken strips for 4–5 minutes until cooked through.',
      'Pour sauce over the chicken and toss to coat; cook 1 more minute.',
      'Scatter spring onions and sesame seeds on top and serve over rice.',
    ],
    totalMinutes: 20,
    searchableIngredients: ['chicken', 'soy sauce', 'honey', 'garlic', 'sesame oil', 'spring onions'],
  },
  {
    id: 'sheet-pan-chicken-fajitas',
    title: 'Sheet-Pan Chicken Fajitas',
    servings: 4,
    ingredients: [
      { name: 'chicken', quantity: 600, unit: 'g' },
      { name: 'bell peppers', quantity: 3, unit: 'piece' },
      { name: 'red onion', quantity: 1, unit: 'piece' },
      { name: 'olive oil', quantity: 3, unit: 'tbsp' },
      { name: 'cumin', quantity: 1, unit: 'tsp' },
      { name: 'smoked paprika', quantity: 1, unit: 'tsp' },
      { name: 'flour tortillas', quantity: 8, unit: 'piece' },
    ],
    steps: [
      'Preheat oven to 220°C (425°F).',
      'Slice chicken, peppers, and onion into thin strips.',
      'Toss everything with olive oil, cumin, smoked paprika, and salt.',
      'Spread in a single layer on a large sheet pan.',
      'Roast for 20 minutes, flipping once halfway through.',
      'Warm tortillas and serve with the chicken and vegetables.',
    ],
    totalMinutes: 30,
    searchableIngredients: ['chicken', 'bell peppers', 'red onion', 'olive oil', 'cumin', 'paprika', 'tortillas'],
  },
  {
    id: 'creamy-mushroom-risotto',
    title: 'Creamy Mushroom Risotto',
    servings: 4,
    ingredients: [
      { name: 'arborio rice', quantity: 320, unit: 'g' },
      { name: 'mushrooms', quantity: 250, unit: 'g' },
      { name: 'vegetable stock', quantity: 1000, unit: 'ml' },
      { name: 'white wine', quantity: 120, unit: 'ml' },
      { name: 'parmesan', quantity: 60, unit: 'g' },
      { name: 'butter', quantity: 2, unit: 'tbsp' },
      { name: 'shallots', quantity: 2, unit: 'piece' },
    ],
    steps: [
      'Warm vegetable stock in a saucepan and keep it at a gentle simmer.',
      'Sauté finely chopped shallots in butter over medium heat until soft.',
      'Slice mushrooms and cook with the shallots until golden, about 5 minutes.',
      'Add arborio rice and stir for 1 minute to coat the grains.',
      'Pour in wine and stir until absorbed, then add stock one ladle at a time.',
      'Continue adding stock and stirring for 20 minutes until rice is tender.',
      'Remove from heat, fold in grated parmesan, and serve immediately.',
    ],
    totalMinutes: 45,
    searchableIngredients: ['arborio rice', 'mushrooms', 'vegetable stock', 'white wine', 'parmesan', 'butter', 'shallots'],
  },
  {
    id: 'salmon-teriyaki',
    title: 'Salmon Teriyaki',
    servings: 2,
    ingredients: [
      { name: 'salmon fillets', quantity: 2, unit: 'piece' },
      { name: 'soy sauce', quantity: 3, unit: 'tbsp' },
      { name: 'mirin', quantity: 2, unit: 'tbsp' },
      { name: 'honey', quantity: 1, unit: 'tbsp' },
      { name: 'sesame oil', quantity: 1, unit: 'tsp' },
      { name: 'spring onions', quantity: 2, unit: 'piece' },
    ],
    steps: [
      'Mix soy sauce, mirin, and honey in a small bowl to make the teriyaki glaze.',
      'Heat sesame oil in a non-stick pan over medium-high heat.',
      'Cook salmon skin-side up for 3 minutes, then flip.',
      'Pour teriyaki glaze over the salmon and cook 3–4 more minutes, basting frequently.',
      'Garnish with sliced spring onions and serve with steamed rice.',
    ],
    totalMinutes: 25,
    searchableIngredients: ['salmon', 'soy sauce', 'mirin', 'honey', 'sesame oil', 'spring onions'],
  },
  {
    id: 'beef-tacos',
    title: 'Quick Beef Tacos',
    servings: 4,
    ingredients: [
      { name: 'ground beef', quantity: 500, unit: 'g' },
      { name: 'corn tortillas', quantity: 8, unit: 'piece' },
      { name: 'cumin', quantity: 1, unit: 'tsp' },
      { name: 'chili powder', quantity: 1, unit: 'tsp' },
      { name: 'cheddar cheese', quantity: 80, unit: 'g' },
      { name: 'salsa', quantity: 4, unit: 'tbsp' },
      { name: 'sour cream', quantity: 4, unit: 'tbsp' },
    ],
    steps: [
      'Brown ground beef in a skillet over medium-high heat, breaking it apart.',
      'Drain excess fat, then season with cumin, chili powder, and salt.',
      'Cook for 2 more minutes until spices are fragrant.',
      'Warm tortillas in a dry pan or directly over the gas flame.',
      'Fill tortillas with beef, shredded cheese, salsa, and sour cream.',
    ],
    totalMinutes: 20,
    searchableIngredients: ['ground beef', 'corn tortillas', 'cumin', 'chili powder', 'cheddar cheese', 'salsa'],
  },
  {
    id: 'greek-salad',
    title: 'Greek Salad with Feta',
    servings: 2,
    ingredients: [
      { name: 'cucumber', quantity: 1, unit: 'piece' },
      { name: 'cherry tomatoes', quantity: 200, unit: 'g' },
      { name: 'red onion', quantity: 0.5, unit: 'piece' },
      { name: 'feta cheese', quantity: 100, unit: 'g' },
      { name: 'kalamata olives', quantity: 60, unit: 'g' },
      { name: 'olive oil', quantity: 3, unit: 'tbsp' },
      { name: 'dried oregano', quantity: 1, unit: 'tsp' },
    ],
    steps: [
      'Chop cucumber into chunks and halve the cherry tomatoes.',
      'Thinly slice red onion.',
      'Combine vegetables and olives in a large bowl.',
      'Crumble feta over the top.',
      'Drizzle with olive oil, sprinkle oregano, and season with salt; toss gently.',
    ],
    totalMinutes: 15,
    searchableIngredients: ['cucumber', 'tomatoes', 'red onion', 'feta', 'olives', 'olive oil', 'oregano'],
  },
  {
    id: 'shrimp-scampi',
    title: 'Shrimp Scampi',
    servings: 2,
    ingredients: [
      { name: 'shrimp', quantity: 400, unit: 'g' },
      { name: 'linguine', quantity: 200, unit: 'g' },
      { name: 'garlic cloves', quantity: 4, unit: 'piece' },
      { name: 'butter', quantity: 3, unit: 'tbsp' },
      { name: 'white wine', quantity: 60, unit: 'ml' },
      { name: 'lemon', quantity: 1, unit: 'piece' },
      { name: 'fresh parsley', quantity: 3, unit: 'tbsp' },
    ],
    steps: [
      'Cook linguine in salted boiling water until al dente; reserve ½ cup pasta water.',
      'Peel and devein shrimp, then pat dry.',
      'Melt butter in a skillet over medium heat and sauté garlic for 1 minute.',
      'Add shrimp and cook 2 minutes per side until pink.',
      'Pour in white wine and lemon juice; cook 1 minute.',
      'Toss in drained pasta and a splash of pasta water to coat; garnish with parsley.',
    ],
    totalMinutes: 20,
    searchableIngredients: ['shrimp', 'linguine', 'garlic', 'butter', 'white wine', 'lemon', 'parsley'],
  },
  {
    id: 'veggie-curry',
    title: 'Chickpea and Spinach Curry',
    servings: 4,
    ingredients: [
      { name: 'chickpeas', quantity: 400, unit: 'g' },
      { name: 'spinach', quantity: 200, unit: 'g' },
      { name: 'canned tomatoes', quantity: 400, unit: 'g' },
      { name: 'coconut milk', quantity: 200, unit: 'ml' },
      { name: 'onion', quantity: 1, unit: 'piece' },
      { name: 'garam masala', quantity: 2, unit: 'tsp' },
      { name: 'cumin', quantity: 1, unit: 'tsp' },
    ],
    steps: [
      'Dice onion and sauté in oil over medium heat until softened.',
      'Add garam masala and cumin; stir for 1 minute until fragrant.',
      'Pour in canned tomatoes and coconut milk; bring to a simmer.',
      'Add drained chickpeas and cook for 15 minutes.',
      'Stir in spinach and cook until wilted, about 2 minutes.',
      'Season with salt and serve with basmati rice or naan.',
    ],
    totalMinutes: 35,
    searchableIngredients: ['chickpeas', 'spinach', 'tomatoes', 'coconut milk', 'onion', 'garam masala', 'cumin'],
  },
  {
    id: 'avocado-toast-eggs',
    title: 'Avocado Toast with Poached Eggs',
    servings: 2,
    ingredients: [
      { name: 'sourdough bread', quantity: 2, unit: 'piece' },
      { name: 'avocado', quantity: 1, unit: 'piece' },
      { name: 'eggs', quantity: 2, unit: 'piece' },
      { name: 'lemon juice', quantity: 1, unit: 'tbsp' },
      { name: 'chili flakes', quantity: 0.5, unit: 'tsp' },
      { name: 'salt', quantity: 0.5, unit: 'tsp' },
    ],
    steps: [
      'Toast sourdough slices until golden and crisp.',
      'Mash avocado with lemon juice and salt.',
      'Bring a shallow pan of water to a gentle simmer; add a splash of white vinegar.',
      'Crack each egg into the water and poach for 3 minutes until whites are set.',
      'Spread mashed avocado on toast, top with a poached egg, and sprinkle chili flakes.',
    ],
    totalMinutes: 15,
    searchableIngredients: ['sourdough', 'avocado', 'eggs', 'lemon juice', 'chili flakes', 'salt'],
  },
];
